#!/bin/sh

sass --compass --update -t expanded -f bartlett:bartlett
sass --compass --update -t expanded -f bartlett_flipped:bartlett_flipped
sass --compass --update -t expanded -f boxton:boxton
sass --compass --update -t expanded -f brenham:brenham
sass --compass --update -t expanded -f brenham_flipped:brenham_flipped
sass --compass --update -t expanded -f brown:brown
sass --compass --update -t expanded -f bryant:bryant
sass --compass --update -t expanded -f bryant_flipped:bryant_flipped
sass --compass --update -t expanded -f burr:burr
sass --compass --update -t expanded -f burr_flipped:burr_flipped
sass --compass --update -t expanded -f geary:geary
sass --compass --update -t expanded -f harris:harris
sass --compass --update -t expanded -f hewston:hewston
sass --compass --update -t expanded -f hewston_flipped:hewston_flipped
sass --compass --update -t expanded -f mccoppin:mccoppin
sass --compass --update -t expanded -f moscone:moscone
sass --compass --update -t expanded -f moscone_flipped:moscone_flipped
sass --compass --update -t expanded -f phelan:phelan
sass --compass --update -t expanded -f pond:pond
sass --compass --update -t expanded -f rolph:rolph
sass --compass --update -t expanded -f sanderson:sanderson
sass --compass --update -t expanded -f sanderson_flipped:sanderson_flipped
sass --compass --update -t expanded -f selby:selby
sass --compass --update -t expanded -f selby_flipped:selby_flipped
sass --compass --update -t expanded -f sutro:sutro
sass --compass --update -t expanded -f sutro_double:sutro_double
sass --compass --update -t expanded -f taylor:taylor
sass --compass --update -t expanded -f taylor_flipped:taylor_flipped
sass --compass --update -t expanded -f webb:webb
sass --compass --update -t expanded -f webb_flipped:webb_flipped
sass --compass --update -t expanded -f whelan:whelan
